services:
#    redstar_security.example:
#        class: Redstar\SecurityBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    kernel.listener.security:
               class: Redstar\SecurityBundle\EventListeners\SecurityRequestListener
               arguments: ["@security.context"]
               tags:
                   - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }



