services:
    redstar_menu_builder:
        class: Redstar\SkeletonAppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    redstar_main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: redstar_menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

